// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.0

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	solBlocksFieldNames          = builder.RawFieldNames(&SolBlocks{})
	solBlocksRows                = strings.Join(solBlocksFieldNames, ",")
	solBlocksRowsExpectAutoSet   = strings.Join(stringx.Remove(solBlocksFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	solBlocksRowsWithPlaceHolder = strings.Join(stringx.Remove(solBlocksFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	solBlocksModel interface {
		Insert(ctx context.Context, data *SolBlocks) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*SolBlocks, error)
		FindOneByChainIdSlot(ctx context.Context, chainId int64, slot uint64) (*SolBlocks, error)
		Update(ctx context.Context, data *SolBlocks) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultSolBlocksModel struct {
		conn  sqlx.SqlConn
		table string
	}

	SolBlocks struct {
		Id                uint64         `db:"id"`
		ChainId           int64          `db:"chain_id"`
		Slot              uint64         `db:"slot"`
		BlockHeight       sql.NullInt64  `db:"block_height"`
		ParentSlot        sql.NullInt64  `db:"parent_slot"`
		BlockHash         sql.NullString `db:"block_hash"`
		PreviousBlockHash sql.NullString `db:"previous_block_hash"`
		BlockTime         sql.NullTime   `db:"block_time"`
		TxCount           int64          `db:"tx_count"`
		Status            int64          `db:"status"`
		ErrMsg            sql.NullString `db:"err_msg"`
		CreatedAt         time.Time      `db:"created_at"`
		UpdatedAt         time.Time      `db:"updated_at"`
	}
)

func newSolBlocksModel(conn sqlx.SqlConn) *defaultSolBlocksModel {
	return &defaultSolBlocksModel{
		conn:  conn,
		table: "`sol_blocks`",
	}
}

func (m *defaultSolBlocksModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultSolBlocksModel) FindOne(ctx context.Context, id uint64) (*SolBlocks, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", solBlocksRows, m.table)
	var resp SolBlocks
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSolBlocksModel) FindOneByChainIdSlot(ctx context.Context, chainId int64, slot uint64) (*SolBlocks, error) {
	var resp SolBlocks
	query := fmt.Sprintf("select %s from %s where `chain_id` = ? and `slot` = ? limit 1", solBlocksRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, chainId, slot)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSolBlocksModel) Insert(ctx context.Context, data *SolBlocks) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, solBlocksRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ChainId, data.Slot, data.BlockHeight, data.ParentSlot, data.BlockHash, data.PreviousBlockHash, data.BlockTime, data.TxCount, data.Status, data.ErrMsg)
	return ret, err
}

func (m *defaultSolBlocksModel) Update(ctx context.Context, newData *SolBlocks) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, solBlocksRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.ChainId, newData.Slot, newData.BlockHeight, newData.ParentSlot, newData.BlockHash, newData.PreviousBlockHash, newData.BlockTime, newData.TxCount, newData.Status, newData.ErrMsg, newData.Id)
	return err
}

func (m *defaultSolBlocksModel) tableName() string {
	return m.table
}
