// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.0

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	solSwapsFieldNames          = builder.RawFieldNames(&SolSwaps{})
	solSwapsRows                = strings.Join(solSwapsFieldNames, ",")
	solSwapsRowsExpectAutoSet   = strings.Join(stringx.Remove(solSwapsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	solSwapsRowsWithPlaceHolder = strings.Join(stringx.Remove(solSwapsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	solSwapsModel interface {
		Insert(ctx context.Context, data *SolSwaps) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*SolSwaps, error)
		Update(ctx context.Context, data *SolSwaps) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultSolSwapsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	SolSwaps struct {
		Id             uint64          `db:"id"`
		ChainId        int64           `db:"chain_id"`
		Slot           uint64          `db:"slot"`
		TxHash         string          `db:"tx_hash"`
		DexName        string          `db:"dex_name"`
		SwapType       sql.NullString  `db:"swap_type"`
		PoolAddress    sql.NullString  `db:"pool_address"`
		UserAddress    sql.NullString  `db:"user_address"`
		BaseMint       sql.NullString  `db:"base_mint"`
		QuoteMint      sql.NullString  `db:"quote_mint"`
		BaseAmount     sql.NullFloat64 `db:"base_amount"`
		QuoteAmount    sql.NullFloat64 `db:"quote_amount"`
		BaseAmountRaw  sql.NullInt64   `db:"base_amount_raw"`
		QuoteAmountRaw sql.NullInt64   `db:"quote_amount_raw"`
		FeeLamports    sql.NullInt64   `db:"fee_lamports"`
		BlockTime      sql.NullTime    `db:"block_time"`
		CreatedAt      time.Time       `db:"created_at"`
		UpdatedAt      time.Time       `db:"updated_at"`
	}
)

func newSolSwapsModel(conn sqlx.SqlConn) *defaultSolSwapsModel {
	return &defaultSolSwapsModel{
		conn:  conn,
		table: "`sol_swaps`",
	}
}

func (m *defaultSolSwapsModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultSolSwapsModel) FindOne(ctx context.Context, id uint64) (*SolSwaps, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", solSwapsRows, m.table)
	var resp SolSwaps
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSolSwapsModel) Insert(ctx context.Context, data *SolSwaps) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, solSwapsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ChainId, data.Slot, data.TxHash, data.DexName, data.SwapType, data.PoolAddress, data.UserAddress, data.BaseMint, data.QuoteMint, data.BaseAmount, data.QuoteAmount, data.BaseAmountRaw, data.QuoteAmountRaw, data.FeeLamports, data.BlockTime)
	return ret, err
}

func (m *defaultSolSwapsModel) Update(ctx context.Context, data *SolSwaps) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, solSwapsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.ChainId, data.Slot, data.TxHash, data.DexName, data.SwapType, data.PoolAddress, data.UserAddress, data.BaseMint, data.QuoteMint, data.BaseAmount, data.QuoteAmount, data.BaseAmountRaw, data.QuoteAmountRaw, data.FeeLamports, data.BlockTime, data.Id)
	return err
}

func (m *defaultSolSwapsModel) tableName() string {
	return m.table
}
