// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.0

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	solTransactionsFieldNames          = builder.RawFieldNames(&SolTransactions{})
	solTransactionsRows                = strings.Join(solTransactionsFieldNames, ",")
	solTransactionsRowsExpectAutoSet   = strings.Join(stringx.Remove(solTransactionsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	solTransactionsRowsWithPlaceHolder = strings.Join(stringx.Remove(solTransactionsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	solTransactionsModel interface {
		Insert(ctx context.Context, data *SolTransactions) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*SolTransactions, error)
		FindOneByChainIdTxHash(ctx context.Context, chainId int64, txHash string) (*SolTransactions, error)
		Update(ctx context.Context, data *SolTransactions) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultSolTransactionsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	SolTransactions struct {
		Id        uint64         `db:"id"`
		ChainId   int64          `db:"chain_id"`
		Slot      uint64         `db:"slot"`
		TxHash    string         `db:"tx_hash"`
		Signer    sql.NullString `db:"signer"`
		Program   sql.NullString `db:"program"`
		DexName   sql.NullString `db:"dex_name"`
		Success   int64          `db:"success"`
		BlockTime sql.NullTime   `db:"block_time"`
		RawJson   sql.NullString `db:"raw_json"`
		CreatedAt time.Time      `db:"created_at"`
		UpdatedAt time.Time      `db:"updated_at"`
	}
)

func newSolTransactionsModel(conn sqlx.SqlConn) *defaultSolTransactionsModel {
	return &defaultSolTransactionsModel{
		conn:  conn,
		table: "`sol_transactions`",
	}
}

func (m *defaultSolTransactionsModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultSolTransactionsModel) FindOne(ctx context.Context, id uint64) (*SolTransactions, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", solTransactionsRows, m.table)
	var resp SolTransactions
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSolTransactionsModel) FindOneByChainIdTxHash(ctx context.Context, chainId int64, txHash string) (*SolTransactions, error) {
	var resp SolTransactions
	query := fmt.Sprintf("select %s from %s where `chain_id` = ? and `tx_hash` = ? limit 1", solTransactionsRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, chainId, txHash)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSolTransactionsModel) Insert(ctx context.Context, data *SolTransactions) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, solTransactionsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ChainId, data.Slot, data.TxHash, data.Signer, data.Program, data.DexName, data.Success, data.BlockTime, data.RawJson)
	return ret, err
}

func (m *defaultSolTransactionsModel) Update(ctx context.Context, newData *SolTransactions) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, solTransactionsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.ChainId, newData.Slot, newData.TxHash, newData.Signer, newData.Program, newData.DexName, newData.Success, newData.BlockTime, newData.RawJson, newData.Id)
	return err
}

func (m *defaultSolTransactionsModel) tableName() string {
	return m.table
}
